version: "3"

services:
  node:
    build: .
    user: node
    working_dir: /app
    volumes:
      - ./:/app
    container_name: back_end_jus
    tty: true
    stdin_open: true
    command: bash
    restart: always
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      HOSTNAME: db
  db:
    container_name: back_end_jus_db
    image: mysql:8.0.21
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password

networks:
  default:
    name: back_end_jus_net